sudo: required
language: generic

services:
  - docker

# Set environment variable COALA_BRANCH=<branch> to override
# the default.

install:
  - export COALA_BRANCH=$(python guess_branch.py "$TRAVIS_BRANCH") && echo $COALA_BRANCH
  - docker build -f Dockerfile --build-arg branch=$COALA_BRANCH -t coala-docker .

script:
  - docker images
  - >
    docker run -t -i coala-docker /bin/sh -c "
      set -e -x
      export OS_NAME=posix;
      cd /coala; python3 -m pytest;
      cd /coala-bears;
      rm bears/Constants.py;  # There are no tests covering this module
      rm bears/c_languages/CSharpLintBear.py tests/c_languages/CSharpLintBearTest.py;
      rm bears/java/InferBear.py tests/java/InferBearTest.py;
      rm bears/haskell/GhcModBear.py tests/haskell/GhcModBearTest.py;
      rm -r bears/verilog tests/verilog/;
      python3 -m pytest --cov --cov-fail-under=100;
      cd /tmp;
      svn co https://github.com/githubtraining/hellogitworld.git;
      bzr branch lp:govcstestbzrrepo;
      hg clone https://bitbucket.org/fracai/empty-hg;
    "
  # Verify MarkdownBear works outside of coala-bears directory.
  # See https://github.com/coala/coala-bears/issues/1235
  - >
    docker run -t -i coala-docker /bin/sh -c "
      cd /tmp;
      echo foo > foo.md;
      coala --non-interactive --no-config --bears MarkdownBear --files foo.md;
    "
  - /bin/sh -c "! docker run coala-docker"
  - docker run --volume=$(pwd)/.ci/sample:/work --workdir=/work coala-docker
  - ls -la ./.ci/sample/.coafile
  - sudo chown $USER ./.ci/sample/.coafile
  - echo -e "[fail]\nbears = NoCommentsBear\nfile = **.py" >> ./.ci/sample/.coafile
  - /bin/sh -c "! docker run --volume=$(pwd)/.ci/sample:/work --volume=$(pwd)/.ci/bears:/additional_bears --workdir=/work coala-docker"
notifications:
  email: false
