sudo: required

services:
  - docker

install:
  - docker build -f Dockerfile -t coala-docker .
  - docker images

script:
  - docker run -t -i coala-docker /bin/sh -c "cd /coala; python3 -m pytest -k 'not Dbus' --cov"

notifications:
  email: false
