sudo: required

services:
  - docker

install:
  - docker build -f Dockerfile -t coala-docker .
  - docker images

script:
  - >
    docker run -t -i coala-docker /bin/sh -c "
      cd /coala; python3 -m pytest --cov --cov-fail-under=100;
      cd /coala-bears;
      rm bears/Constants.py;  # There are no tests covering this module
      rm bears/c_languages/CSharpLintBear.py tests/c_languages/CSharpLintBearTest.py;
      rm bears/java/InferBear.py tests/java/InferBearTest.py;
      rm -r bears/verilog tests/verilog/;
      python3 -m pytest --cov --cov-fail-under=100
    "
  - /bin/sh -c "! docker run coala-docker"
  - docker run --volume=$(pwd)/.ci:/work --workdir=/work coala-docker
  - ls -la ./.ci/.coafile
notifications:
  email: false
